#!/bin/zsh

# - Will need to be able to fetch HTML
#   - Maybe we want to cache it
# - Will need to be able to parse the HTML in certain ways
#   - First sentence of article
#   - Article sections
#   - Recursive -- article sections will need first sentence, and may have subsections

echo "$0 $1 $2 $3 $4"

# Capitalize first character of $1
first=`echo $1 | colrm 2`
rest=`echo $1 | colrm 1 1`
capitalized=`echo $first | tr '[a-z]' '[A-Z]'`$rest


# Check if we have the html page cached
if [[ -e $1.html ]]
  then
    echo "$1 exists."
  else
    echo "Fetching $1"
    curl "https://en.wikipedia.org/wiki/$capitalized" > $1.html
fi